(() => {
  'use strict';
  const templates=[...document.querySelector('#pages').content.querySelectorAll('article')];
  templates.forEach(p=>{p.classList.remove('left','right','page');p.classList.add('page-art');p.querySelectorAll('.pattern').forEach(el=>{for(let n=0;n<40;n++)el.append(document.createElement('i'))});p.querySelectorAll('[data-edit]').forEach(el=>el.removeAttribute('contenteditable'));if(!p.querySelector('.strip')){const line=document.createElement('div');line.className='footer-rule';p.append(line)}});
  const canvas=document.querySelector('.flip-canvas'),stage=document.querySelector('.flip-stage'),selector=document.querySelector('#page-select'),prev=document.querySelector('#previous'),next=document.querySelector('#next-page');
  const groups=[[null,0],[1,2],[3,4],[5,6],[7,8],[9,10]];
  let mobile=matchMedia('(max-width:700px)').matches,current=0,scale=1,turn=null,animating=false,pointer=null,zoom=false;
  const reduced=matchMedia('(prefers-reduced-motion:reduce)');
  function page(n){return n==null?null:templates[n].cloneNode(true)}
  function slots(index){return mobile?[index]:groups[index]}
  function max(){return mobile?templates.length-1:groups.length-1}
  function base(n,x){const el=document.createElement('div');el.className='base-page'+(n==null?' empty':'');el.style.left=x+'px';if(n!=null)el.append(page(n));canvas.append(el);return el}
  function face(n,kind){const el=document.createElement('div');el.className='leaf-face '+kind;if(n!=null)el.append(page(n));else el.style.background='#dfddd7';return el}
  function label(index){if(mobile)return index===0?'Cover':'Page '+String(index+1).padStart(2,'0');if(index===0)return 'Cover';return 'Pages '+String(groups[index][0]+1).padStart(2,'0')+'–'+String(groups[index][1]+1).padStart(2,'0')}
  function update(){prev.disabled=current===0||animating;next.disabled=current===max()||animating;selector.value=String(current);document.querySelector('#page-status').textContent=label(current)+' / 11';document.querySelector('#progress').style.width=((current+1)/(max()+1)*100)+'%';document.querySelector('#gesture-hint').textContent=zoom?'Scroll to inspect the page · Tap Fit to return':mobile?'Swipe left or right to turn the page':'Drag a page, use the arrows, or press ← →';document.querySelector('#view-label').textContent=mobile?'MOBILE EDITION':'FACING-PAGE EDITION';document.querySelector('#zoom').textContent=zoom?'Fit':'Zoom';document.querySelector('#zoom').setAttribute('aria-pressed',zoom);stage.setAttribute('aria-label',label(current)+'. Swipe left for next page or right for previous page.');}
  function setOptions(){selector.innerHTML='';for(let i=0;i<=max();i++){const opt=document.createElement('option');opt.value=i;opt.textContent=label(i);selector.append(opt)}}
  function render(){canvas.replaceChildren();slots(current).forEach((n,i)=>base(n,i*595));if(!mobile&&current!==0){const g=document.createElement('div');g.className='gutter';canvas.append(g)}update()}
  function fit(){const nextMobile=matchMedia('(max-width:700px)').matches;if(nextMobile!==mobile){const actual=mobile?current:(groups[current].find(n=>n!=null)||0);mobile=nextMobile;current=mobile?actual:actual===0?0:Math.ceil(actual/2);turn=null;animating=false;setOptions();render()}
    document.body.classList.toggle('mobile',mobile);document.body.classList.toggle('read-zoom',zoom);
    const units=mobile?595:1190,w=innerWidth-(mobile?20:48),h=innerHeight-(mobile?193:210);scale=Math.min(w/units,Math.max(180,h)/842);if(zoom)scale=Math.max(scale*1.8,mobile?.95:1.1);stage.style.width=units*scale+'px';stage.style.height=842*scale+'px';canvas.style.transform=`scale(${scale})`;canvas.style.width=units+'px';update();}
  function begin(dir){if(animating||turn||zoom||current+dir<0||current+dir>max())return false;const target=current+dir,a=slots(current),b=slots(target);canvas.replaceChildren();let front,back;if(mobile){base(b[0],0);front=a[0];back=b[0]}else if(dir===1){base(a[0],0);base(b[1],595);front=a[1];back=b[0]}else{base(b[0],0);base(a[1],595);front=a[0];back=b[1]}
    const leaf=document.createElement('div');leaf.className='leaf '+(dir===1?'forward':'backward');leaf.append(face(front,'front'),face(back,'back'));canvas.append(leaf);turn={dir,target,leaf,progress:0};progress(0);return true}
  function progress(p){if(!turn)return;turn.progress=Math.max(0,Math.min(1,p));const a=turn.progress*180*turn.dir*-1;turn.leaf.style.transform=mobile?`translateX(${595*turn.progress}px) rotateY(${-180*turn.progress}deg)`:`rotateY(${a}deg)`;turn.leaf.style.setProperty('--shade',String(Math.sin(turn.progress*Math.PI)*.95))}
  function finish(commit=true){if(!turn)return;animating=true;update();const from=turn.progress,to=commit?1:0,start=performance.now(),duration=reduced.matches?0:Math.max(170,650*Math.abs(to-from));const thisTurn=turn;function frame(now){if(turn!==thisTurn)return;const t=duration===0?1:Math.min(1,(now-start)/duration),ease=1-Math.pow(1-t,3);progress(from+(to-from)*ease);if(t<1)requestAnimationFrame(frame);else{if(commit)current=turn.target;turn=null;animating=false;render();history.replaceState(null,'','#page='+String((mobile?current:(groups[current].find(n=>n!=null)||0))+1));}}requestAnimationFrame(frame)}
  function go(dir){if(zoom){zoom=false;fit()}if(begin(dir))finish(true)}
  stage.addEventListener('pointerdown',e=>{if(animating||zoom||e.button!==0)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,last:e.clientX,t:performance.now(),drag:false};});
  stage.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(!pointer.drag){if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>12){pointer=null;return}if(Math.abs(dx)<12)return;if(!begin(dx<0?1:-1)){pointer=null;return}pointer.drag=true;stage.setPointerCapture(e.pointerId)}progress(Math.abs(dx)/(595*scale));pointer.last=e.clientX;});
  function release(e){if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,elapsed=performance.now()-pointer.t;if(pointer.drag&&turn)finish(turn.progress>.18||(Math.abs(dx)>35&&elapsed<400));pointer=null;}
  stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',()=>{if(turn&&!animating)finish(false);pointer=null});stage.addEventListener('lostpointercapture',()=>{if(pointer){if(turn&&!animating)finish(false);pointer=null}});
  prev.onclick=()=>go(-1);next.onclick=()=>go(1);selector.onchange=()=>{if(animating){selector.value=current;return}current=Number(selector.value);turn=null;render();history.replaceState(null,'','#page='+((mobile?current:(groups[current].find(n=>n!=null)||0))+1))};
  document.addEventListener('keydown',e=>{if(e.target.matches('select,input,textarea')||document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(1)}if(e.key==='ArrowLeft'){e.preventDefault();go(-1)}if(e.key==='Home'){current=0;render()}if(e.key==='End'){current=max();render()}});
  document.querySelector('#zoom').onclick=()=>{if(animating||turn)return;zoom=!zoom;fit()};
  document.querySelector('#review-info').onclick=()=>document.querySelector('dialog').showModal();document.querySelector('#close-info').onclick=()=>document.querySelector('dialog').close();
  let toastTimer;function toast(s){const el=document.querySelector('#share-status');el.textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.textContent='',4000)}
  document.querySelector('#share').onclick=async()=>{const url=location.href;try{if(navigator.share){await navigator.share({title:'MEGA Catalogue — Client Review',text:'Review the Mega commercial catalogue.',url})}else if(navigator.clipboard&&location.protocol!=='file:'){await navigator.clipboard.writeText(url);toast('Review link copied')}else{prompt('Copy this review link:',url)}}catch(e){if(e.name!=='AbortError')toast('Copy the address from your browser to share.')}};
  const hash=Number(new URLSearchParams(location.hash.slice(1)).get('page'));if(hash>=1&&hash<=templates.length)current=mobile?hash-1:hash===1?0:Math.ceil((hash-1)/2);
  setOptions();render();fit();addEventListener('resize',fit);document.fonts.ready.then(fit);
})();
